name: Build, Push to ECR and Deploy


on:
  push:
    branches:
      - main


jobs:

  deploy:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven


      - name: Build Maven Project
        run: mvn clean package -DskipTests


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1


      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2


      - name: Build Docker Image
        run: |
          docker build -t notes-app .
          docker tag notes-app:latest 236782813851.dkr.ecr.us-east-1.amazonaws.com/notes-app:latest


      - name: Push Docker Image
        run: |
          docker push 236782813851.dkr.ecr.us-east-1.amazonaws.com/notes-app:latest


      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |

            echo "Login to ECR"

            aws ecr get-login-password --region us-east-1 | \
            docker login \
            --username AWS \
            --password-stdin \
            236782813851.dkr.ecr.us-east-1.amazonaws.com


            echo "Pull latest image"

            docker pull 236782813851.dkr.ecr.us-east-1.amazonaws.com/notes-app:latest


            echo "Stop old container"

            docker stop notes-app || true
            docker rm notes-app || true


            echo "Start new container"

            docker run -d \
            --name notes-app \
            -p 8080:8080 \
            --restart always \
            236782813851.dkr.ecr.us-east-1.amazonaws.com/notes-app:latest


            echo "Deployment completed"